services:
  erp-backend:
    image: erp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads

  erp-frontend:
    image: erp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - erp-backend
