
-- Admin gets all permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT 
    r.id, 
    p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'admin'
AND p.name IN (
    'FACTORY_MATERIAL_ALLOCATIONS_READ',
    'FACTORY_MATERIAL_ALLOCATIONS_CREATE',
    'FACTORY_MATERIAL_ALLOCATIONS_UPDATE',
    'FACTORY_MATERIAL_ALLOCATIONS_DELETE',
    'FACTORY_MATERIAL_CONSUMPTIONS_READ',
    'FACTORY_MATERIAL_CONSUMPTIONS_CREATE',
    'FACTORY_WASTAGE_READ',
    'FACTORY_WASTAGE_APPROVE',
    'FACTORY_PRODUCTION_RUNS_READ',
    'FACTORY_PRODUCTION_RUNS_CREATE',
    'FACTORY_PRODUCTION_RUNS_UPDATE',
    'FACTORY_PRODUCTION_RUNS_DELETE',
    'FACTORY_DASHBOARD_READ'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;